ReConBotPub Class Reference
#include <ReConBot.h>
Public Member Functions
ReConBotPub ()
control_msgs::FollowJointTrajectoryGoal buildTrajectory ()
void trajectoryPublisherStart (ros::NodeHandle &nh, int topicQuery)
void publisher (control_msgs::FollowJointTrajectoryGoal goal)
void motorsState (int arg[], int length)
void reconbotCallback (const control_msgs::FollowJointTrajectoryGoal goal)
void trajClient ()
void startTrajectory (control_msgs::FollowJointTrajectoryGoal goal)
control_msgs::FollowJointTrajectoryGoal armTrajectory ()
bool run ()
actionlib::SimpleClientGoalState getState ()
Returns the current state of the action.
Public Attributes
std::string sourceFile
std::string nameSpace
std::string topicName
Protected Attributes
int cont
int var
int j
float pos
TrajClient * traj_client_
control_msgs::FollowJointTrajectoryGoal goal
ros::NodeHandle nhPub
ros::Publisher nhPub_pub
int topicQuery
std::vector< double > trajectoryPoints
Detailed Description
Definition at line 88 of file ReConBot.h.
Constructor & Destructor Documentation
ReConBotPub()
ReConBotPub::ReConBotPub () [inline]
Definition at line 96 of file ReConBot.h.
References ReConBot::goal, ReConBot::sourceFile, ReConBot::topicName, and ReConBot::topicQuery.
               {
    sourceFile = "/home/jdelacruz/catkin_ws/src/reconbot/trajectory/trajectory1.txt";
    topicName = "/reconbot_trajectory";
  }
Member Function Documentation
armTrajectory()
control_msgs::FollowJointTrajectoryGoal ReConBot::armTrajectory () [inherited]
Referenced by ReConBot::ReConBot().
buildTrajectory()
control_msgs::FollowJointTrajectoryGoal ReConBotPub::buildTrajectory ()
Definition at line 175 of file ReConBot.h.
References ReConBot::goal, motorsActive, nMotors, ReConBot::sourceFile, and ReConBot::trajectoryPoints.
Referenced by main().
                                                                  {
  ROS_INFO("Start building the Trajectory Vector...");
  for (size_t i = 0; i < nMotors; i++) {
    std::stringstream ss;
    ss << motorsActive[i];
    goal.trajectory.joint_names.push_back("joint_"+ ss.str());
  }
  //goal.trajectory.joint_names.push_back("joint_1");
  //goal.trajectory.joint_names.push_back("joint_2");
  //goal.trajectory.joint_names.push_back("joint_3");
  std::fstream pathfile(sourceFile.c_str(), std::ios_base::in);
  int number_of_lines = 0;
  std::string line;
  std::ifstream myfile(sourceFile.c_str());
  while (std::getline(myfile, line)){
      ++number_of_lines;
    }
  goal.trajectory.points.resize(number_of_lines);
  cont =0;
  var =0;
  while (pathfile >> pos && ros::ok()) {
    trajectoryPoints.resize(number_of_lines*(nMotors*3+1));
    trajectoryPoints[var]=pos;
    ++var;
    if (var == nMotors*3 + 1) {
      j = 0;
      for (size_t i = 0; i < nMotors*3; i=i+3) {
        goal.trajectory.points[cont].positions.resize(nMotors);
        goal.trajectory.points[cont].positions[j] = trajectoryPoints[i];
        ++j;
      }
      j = 0;
      for (size_t i = 1; i < nMotors*3; i=i+3) {
        goal.trajectory.points[cont].velocities.resize(nMotors);
        goal.trajectory.points[cont].velocities[j] = trajectoryPoints[i];
        ++j;/* condition */
      }
      j = 0;
      for (size_t i = 2; i < nMotors*3; i=i+3) {
        goal.trajectory.points[cont].accelerations.resize(nMotors);
        goal.trajectory.points[cont].accelerations[j] =
      trajectoryPoints[i];
        if (i == nMotors*3 - 1) {
          goal.trajectory.points[cont].time_from_start = ros::Duration(
      trajectoryPoints[i+1]);
        }
        ++j;
      }
      var = 0;
      ++cont;
      ROS_INFO("New trajectory point created...");
    }
  }
  ROS_INFO("Trajectory vector was successfully built....");
  return goal;
}
getState()
actionlib::SimpleClientGoalState ReConBot::getState () [inherited]
Returns the current state of the action.
Definition at line 147 of file ReConBot.h.
References ReConBot::traj_client_.
Referenced by ReConBot::ReConBot().
                                                 {
  return traj_client_->getState();
}
motorsState()
void ReConBotLx::motorsState (int arg[], int length) [inherited]
Definition at line 136 of file ReConBot.h.
References motorsActive, and nMotors.
Referenced by main().
                                                  {
  // First, the joint names, which apply to all waypoints
  motorsActive = arg;
  nMotors = length;
}
publisher()
void ReConBotPub::publisher (control_msgs::FollowJointTrajectoryGoal goal)
Definition at line 156 of file ReConBot.h.
References ReConBot::nhPub_pub.
Referenced by main().
                                                                     {
  int flag =0;
  while (ros::ok()&&flag==0) {
    ROS_INFO("Waiting for Subscribers...");
  //ros::Rate loop_rate(0.1);
  //nhPub_pub.publish(goal);
  //ros::spinOnce();
  //loop_rate.sleep();
  //ros::spinOnce();
  //ROS_INFO("Goal published");
//}
    if (nhPub_pub.getNumSubscribers()>= 1 && flag == 0) {
      nhPub_pub.publish(goal);
      ros::spinOnce();
      ROS_INFO("Goal published!");
      flag = 1;
    }
  }
}
reconbotCallback()
void ReConBotLx::reconbotCallback (const control_msgs::FollowJointTrajectoryGoal goal) [inherited]
Definition at line 142 of file ReConBot.h.
References ReConBot::startTrajectory().
Referenced by main().
                                                                                 {
      ReConBot::startTrajectory(goal);
  }
run()
bool ReConBot::run () [inherited]
<Two spinner are instantiated for managing 2 threats
Definition at line 118 of file ReConBot.h.
Referenced by ReConBot::ReConBot().
                  {
    ros::AsyncSpinner spinner(2);
    spinner.start();
    ros::waitForShutdown();
}
startTrajectory()
void ReConBot::startTrajectory (control_msgs::FollowJointTrajectoryGoal goal) [inherited]
Sends the command to start a given trajectory
Definition at line 127 of file ReConBot.h.
References ReConBot::traj_client_.
Referenced by ReConBot::ReConBot(), and ReConBotLx::reconbotCallback().
                                                                        {
  ROS_INFO("=========== Welcome to IGM - ReConBot Move Group Interface ==============");
  ROS_INFO("=========== Group of Robotic and Mechatronic ==============");
    // When to start the trajectory: 1s from now
    goal.trajectory.header.stamp = ros::Time::now() + ros::Duration(1.0);
    traj_client_->sendGoal(goal);
  }
trajClient()
void ReConBot::trajClient () [inherited]
tell the action client that we want to spin a thread by default
Definition at line 106 of file ReConBot.h.
References ReConBot::nameSpace, and ReConBot::traj_client_.
Referenced by main(), and ReConBot::ReConBot().
                         {
  traj_client_ = new TrajClient(nameSpace + "/follow_joint_trajectory", true
      );
  // wait for action server to come up
  while(!traj_client_->waitForServer(ros::Duration(5.0))){
  ROS_INFO("Waiting for the joint_trajectory_action server");
  }
}
trajectoryPublisherStart()
void ReConBotPub::trajectoryPublisherStart (ros::NodeHandle & nh, int topicQuery)
Definition at line 151 of file ReConBot.h.
References ReConBot::nhPub, ReConBot::nhPub_pub, ReConBot::topicName, and ReConBot::topicQuery.
Referenced by main().
                                                                           {
  nhPub = nh;
  nhPub_pub = nhPub.advertise<control_msgs::FollowJointTrajectoryGoal>(
      topicName,topicQuery);
}
Member Data Documentation
cont
int ReConBotPub::cont [protected]
Definition at line 90 of file ReConBot.h.
goal
control_msgs::FollowJointTrajectoryGoal ReConBot::goal [protected], [inherited]
Definition at line 60 of file ReConBot.h.
Referenced by buildTrajectory(), ReConBotLx::ReConBotLx(), and ReConBotPub().
j
int ReConBotPub::j [protected]
Definition at line 92 of file ReConBot.h.
nameSpace
std::string ReConBot::nameSpace [inherited]
Definition at line 68 of file ReConBot.h.
Referenced by main(), and ReConBot::trajClient().
nhPub
ros::NodeHandle ReConBot::nhPub [protected], [inherited]
Definition at line 61 of file ReConBot.h.
Referenced by trajectoryPublisherStart().
nhPub_pub
ros::Publisher ReConBot::nhPub_pub [protected], [inherited]
Definition at line 62 of file ReConBot.h.
Referenced by publisher(), and trajectoryPublisherStart().
pos
float ReConBotPub::pos [protected]
Definition at line 93 of file ReConBot.h.
sourceFile
std::string ReConBot::sourceFile [inherited]
File directory with pose data
Definition at line 67 of file ReConBot.h.
Referenced by buildTrajectory(), main(), and ReConBotPub().
topicName
std::string ReConBot::topicName [inherited]
Name given to the topic where is publishing.
Definition at line 69 of file ReConBot.h.
Referenced by main(), ReConBotPub(), and trajectoryPublisherStart().
topicQuery
int ReConBot::topicQuery [protected], [inherited]
Definition at line 63 of file ReConBot.h.
Referenced by ReConBotPub(), and trajectoryPublisherStart().
traj_client_
TrajClient* ReConBot::traj_client_ [protected], [inherited]
Definition at line 59 of file ReConBot.h.
Referenced by ReConBot::getState(), ReConBot::startTrajectory(), and ReConBot::trajClient().
trajectoryPoints
std::vector<double> ReConBot::trajectoryPoints [protected], [inherited]
Definition at line 64 of file ReConBot.h.
Referenced by buildTrajectory().
var
int ReConBotPub::var [protected]
Definition at line 91 of file ReConBot.h.
The documentation for this class was generated from the following file:
ReConBot.h