ReConBotLx Class Reference
#include <ReConBot.h>
Public Member Functions
ReConBotLx ()
void motorsState (int arg[], int length)
void reconbotCallback (const control_msgs::FollowJointTrajectoryGoal goal)
void trajClient ()
void startTrajectory (control_msgs::FollowJointTrajectoryGoal goal)
control_msgs::FollowJointTrajectoryGoal armTrajectory ()
bool run ()
actionlib::SimpleClientGoalState getState ()
Returns the current state of the action.
Public Attributes
std::string sourceFile
std::string nameSpace
std::string topicName
Protected Attributes
TrajClient * traj_client_
control_msgs::FollowJointTrajectoryGoal goal
ros::NodeHandle nhPub
ros::Publisher nhPub_pub
int topicQuery
std::vector< double > trajectoryPoints
Detailed Description
Definition at line 80 of file ReConBot.h.
Constructor & Destructor Documentation
ReConBotLx()
ReConBotLx::ReConBotLx () [inline]
Definition at line 82 of file ReConBot.h.
References ReConBot::goal.
              {
  }
Member Function Documentation
armTrajectory()
control_msgs::FollowJointTrajectoryGoal ReConBot::armTrajectory () [inherited]
Referenced by ReConBot::ReConBot().
getState()
actionlib::SimpleClientGoalState ReConBot::getState () [inherited]
Returns the current state of the action.
Definition at line 147 of file ReConBot.h.
References ReConBot::traj_client_.
Referenced by ReConBot::ReConBot().
                                                 {
  return traj_client_->getState();
}
motorsState()
void ReConBotLx::motorsState (int arg[], int length)
Definition at line 136 of file ReConBot.h.
References motorsActive, and nMotors.
Referenced by main().
                                                  {
  // First, the joint names, which apply to all waypoints
  motorsActive = arg;
  nMotors = length;
}
reconbotCallback()
void ReConBotLx::reconbotCallback (const control_msgs::FollowJointTrajectoryGoal goal)
Definition at line 142 of file ReConBot.h.
References ReConBot::startTrajectory().
Referenced by main().
                                                                                 {
      ReConBot::startTrajectory(goal);
  }
run()
bool ReConBot::run () [inherited]
<Two spinner are instantiated for managing 2 threats
Definition at line 118 of file ReConBot.h.
Referenced by ReConBot::ReConBot().
                  {
    ros::AsyncSpinner spinner(2);
    spinner.start();
    ros::waitForShutdown();
}
startTrajectory()
void ReConBot::startTrajectory (control_msgs::FollowJointTrajectoryGoal goal) [inherited]
Sends the command to start a given trajectory
Definition at line 127 of file ReConBot.h.
References ReConBot::traj_client_.
Referenced by ReConBot::ReConBot(), and reconbotCallback().
                                                                        {
  ROS_INFO("=========== Welcome to IGM - ReConBot Move Group Interface ==============");
  ROS_INFO("=========== Group of Robotic and Mechatronic ==============");
    // When to start the trajectory: 1s from now
    goal.trajectory.header.stamp = ros::Time::now() + ros::Duration(1.0);
    traj_client_->sendGoal(goal);
  }
trajClient()
void ReConBot::trajClient () [inherited]
tell the action client that we want to spin a thread by default
Definition at line 106 of file ReConBot.h.
References ReConBot::nameSpace, and ReConBot::traj_client_.
Referenced by main(), and ReConBot::ReConBot().
                         {
  traj_client_ = new TrajClient(nameSpace + "/follow_joint_trajectory", true
      );
  // wait for action server to come up
  while(!traj_client_->waitForServer(ros::Duration(5.0))){
  ROS_INFO("Waiting for the joint_trajectory_action server");
  }
}
Member Data Documentation
goal
control_msgs::FollowJointTrajectoryGoal ReConBot::goal [protected], [inherited]
Definition at line 60 of file ReConBot.h.
Referenced by ReConBotPub::buildTrajectory(), ReConBotLx(), and ReConBotPub::ReConBotPub().
nameSpace
std::string ReConBot::nameSpace [inherited]
Definition at line 68 of file ReConBot.h.
Referenced by main(), and ReConBot::trajClient().
nhPub
ros::NodeHandle ReConBot::nhPub [protected], [inherited]
Definition at line 61 of file ReConBot.h.
Referenced by ReConBotPub::trajectoryPublisherStart().
nhPub_pub
ros::Publisher ReConBot::nhPub_pub [protected], [inherited]
Definition at line 62 of file ReConBot.h.
Referenced by ReConBotPub::publisher(), and ReConBotPub::trajectoryPublisherStart().
sourceFile
std::string ReConBot::sourceFile [inherited]
File directory with pose data
Definition at line 67 of file ReConBot.h.
Referenced by ReConBotPub::buildTrajectory(), main(), and ReConBotPub::ReConBotPub().
topicName
std::string ReConBot::topicName [inherited]
Name given to the topic where is publishing.
Definition at line 69 of file ReConBot.h.
Referenced by main(), ReConBotPub::ReConBotPub(), and ReConBotPub::trajectoryPublisherStart().
topicQuery
int ReConBot::topicQuery [protected], [inherited]
Definition at line 63 of file ReConBot.h.
Referenced by ReConBotPub::ReConBotPub(), and ReConBotPub::trajectoryPublisherStart().
traj_client_
TrajClient* ReConBot::traj_client_ [protected], [inherited]
Definition at line 59 of file ReConBot.h.
Referenced by ReConBot::getState(), ReConBot::startTrajectory(), and ReConBot::trajClient().
trajectoryPoints
std::vector<double> ReConBot::trajectoryPoints [protected], [inherited]
Definition at line 64 of file ReConBot.h.
Referenced by ReConBotPub::buildTrajectory().
The documentation for this class was generated from the following file:
ReConBot.h