basic_arm.cpp File Reference
#include <ros/ros.h>
#include <control_msgs/FollowJointTrajectoryAction.h>
#include <actionlib/client/simple_action_client.h>
Classes
class ReConBotArm
Typedefs
typedef actionlib::SimpleActionClient< control_msgs::FollowJointTrajectoryAction > TrajClient
Functions
int main (int argc, char **argv)
Typedef Documentation
TrajClient
typedef actionlib::SimpleActionClient<control_msgs::FollowJointTrajectoryAction> TrajClient
Author
Jorge De La Cruz
Version
1.0
Date
February 20, 2017
Definition at line 45 of file basic_arm.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 146 of file basic_arm.cpp.
References ReConBotArm::armTrajectory(), ReConBotArm::getState(), and ReConBotArm::startTrajectory().
{
  // Init the ROS node
  ros::init(argc, argv, "ReConBot_Driver");
  ReConBotArm arm;
  // Start the trajectory
  arm.startTrajectory(arm.armTrajectory());
  // Wait for trajectory completion
  while(!arm.getState().isDone() && ros::ok())
  {
    usleep(8000000);
  }
}