


# the following block is needed for the shared Docker-based runner
image: docker:git # docker and git clients
variables:
  DOCKER_DRIVER: "overlay" # recommended for docker-in-docker, needs overlay kernel module loaded on host
  TMPDIR: "${CI_PROJECT_DIR}.tmp" # needed for prerelease tests with Gitlab's docker-in-docker
services:
  - docker:dind # enable docker-in-docker

before_script:
  - sh -c "echo \"deb http://packages.ros.org/ros/ubuntu lsb_release -cs main\" > /etc/apt/sources.list.d/ros-latest.list"
  - apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - apt-get update -qq
  - apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-indigo-catkin
  - source /opt/ros/indigo/setup.bash
  # Prepare rosdep to install dependencies.
  - rosdep init
  - rosdep update

indigo:
  script:
    - mkdir -p ~/catkin_ws/src
    - cd ~/catkin_ws/src
    - catkin_init_workspace
    - cd ~/catkin_ws/build
    - cmake ../src
    - make
#  variables:
#    ROS_DISTRO: "indigo"
