joint7_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_7
    joint_speed: 1.0
    motor:
        id: 7
        init: 7679
        min: 3584
        max: 11774
