r_arm_trajectory_publisher.cpp File Reference
#include <ros/ros.h>
#include <control_msgs/FollowJointTrajectoryAction.h>
#include <actionlib/client/simple_action_client.h>
#include <iostream>
#include <fstream>
#include `ReConBot.h`
#include <string>
#include <vector>
#include <cstdlib>
#include <map>
#include <pwd.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 15 of file r_arm_trajectory_publisher.cpp.
References ReConBotPub::buildTrajectory(), ReConBotLx::motorsState(), ReConBot::nameSpace, ReConBotPub::publisher(), ReConBot::sourceFile, ReConBot::topicName, and ReConBotPub::trajectoryPublisherStart().
                              {
  ros::init(argc, argv, "r_arm_Trajectory_Publisher");
  ros::NodeHandle nh;
  control_msgs::FollowJointTrajectoryGoal goal;
  //ros::Rate loop_rate(5);
  //ros::AsyncSpinner spinner(1);/**<Two spinner are instantiated for managing 2 threats*/
  //spinner.start();
  ReConBotPub Publisher;
  Publisher.topicName = "/r_arm_reconbot_trajectory";
  int arg[] = {1,2,3};
  passwd* pw = getpwuid(getuid());
  std::string path(pw->pw_dir);
  Publisher.motorsState(arg,3);
  Publisher.trajectoryPublisherStart(nh, 1000);
  Publisher.nameSpace = "r_arm_reconbot_controller";
  Publisher.sourceFile = path += "/catkin_ws/src/reconbot/trajectory/r_arm_trajectory.txt";
  goal = Publisher.buildTrajectory();
  Publisher.publisher(goal);
  sleep(3);
  ROS_INFO("Good bye!");
  //spinner.stop();
  //loop_rate.sleep();
  //sleep(2);
  return 0;
}