ReConBotArm Class Reference
Public Member Functions
ReConBotArm ()
~ReConBotArm ()
Clean up the action client.
void startTrajectory (control_msgs::FollowJointTrajectoryGoal goal)
Sends the command to start a given trajectory.
control_msgs::FollowJointTrajectoryGoal armTrajectory ()
actionlib::SimpleClientGoalState getState ()
Returns the current state of the action.
Private Attributes
TrajClient * traj_client_
Detailed Description
Definition at line 47 of file basic_arm.cpp.
Constructor & Destructor Documentation
ReConBotArm()
ReConBotArm::ReConBotArm () [inline]
Definition at line 52 of file basic_arm.cpp.
  {
    // tell the action client that we want to spin a thread by default
    traj_client_ = new TrajClient("reconbot_arm_controller/follow_joint_trajectory",
      true);
    // wait for action server to come up
    while(!traj_client_->waitForServer(ros::Duration(5.0))){
    ROS_INFO("Waiting for the joint_trajectory_action server");
    }
  }
 ReConBotArm()
ReConBotArm::~ReConBotArm () [inline]
Clean up the action client.
Definition at line 63 of file basic_arm.cpp.
References traj_client_.
  {
  delete traj_client_;
  }
Member Function Documentation
armTrajectory()
control_msgs::FollowJointTrajectoryGoal ReConBotArm::armTrajectory () [inline]
Definition at line 76 of file basic_arm.cpp.
Referenced by main().
    {
      //our goal variable
      control_msgs::FollowJointTrajectoryGoal goal;
      // First, the joint names, which apply to all waypoints
      goal.trajectory.joint_names.push_back("joint_1");
      goal.trajectory.joint_names.push_back("joint_2");
      goal.trajectory.joint_names.push_back("joint_3");
      // We will have two waypoints in this goal trajectory
      goal.trajectory.points.resize(3);
      // First trajectory point
      // Positions
      int ind = 0;
      goal.trajectory.points[ind].positions.resize(3);
      goal.trajectory.points[ind].positions[0] = 0.0;
      goal.trajectory.points[ind].positions[1] = 0.0;
      goal.trajectory.points[ind].positions[2] = 0.4363;
      // Velocities
      goal.trajectory.points[ind].velocities.resize(3);
      for (size_t j = 0; j < 3; ++j)
      {
        goal.trajectory.points[ind].velocities[j] = 0.0;
      }
      // To be reached 1 second after starting along the trajectory
      goal.trajectory.points[ind].time_from_start = ros::Duration(2.0);
      // Second trajectory point
      // Positions
      ind = 1;
      goal.trajectory.points[ind].positions.resize(3);
      goal.trajectory.points[ind].positions[0] = 1.5708;
      goal.trajectory.points[ind].positions[1] = 1.5708;
      goal.trajectory.points[ind].positions[2] = 3.5779;
      // Velocities
      goal.trajectory.points[ind].velocities.resize(3);
      for (size_t j = 0; j < 3; ++j)
      {
        goal.trajectory.points[ind].velocities[j] = 0.0;
      }
      // To be reached 2 seconds after starting along the trajectory
      goal.trajectory.points[ind].time_from_start = ros::Duration(4.0);
      ind = 2;
      goal.trajectory.points[ind].positions.resize(3);
      goal.trajectory.points[ind].positions[0] = 0.0;
      goal.trajectory.points[ind].positions[1] = 0.0;
      goal.trajectory.points[ind].positions[2] = 0.4363;
      // Velocities
      goal.trajectory.points[ind].velocities.resize(3);
      for (size_t j = 0; j < 3; ++j)
      {
        goal.trajectory.points[ind].velocities[j] = 0.0;
      }
      // To be reached 2 seconds after starting along the trajectory
      goal.trajectory.points[ind].time_from_start = ros::Duration(6.0);
      //we are done; return the goal
      return goal;
    }
getState()
actionlib::SimpleClientGoalState ReConBotArm::getState () [inline]
Returns the current state of the action.
Definition at line 140 of file basic_arm.cpp.
Referenced by main().
    {
      return traj_client_->getState();
    }
startTrajectory()
void ReConBotArm::startTrajectory (control_msgs::FollowJointTrajectoryGoal goal) [inline]
Sends the command to start a given trajectory.
Definition at line 68 of file basic_arm.cpp.
Referenced by main().
    {
      // When to start the trajectory: 1s from now
      goal.trajectory.header.stamp = ros::Time::now() + ros::Duration(1.0);
      traj_client_->sendGoal(goal);
    }
Member Data Documentation
traj_client_
TrajClient* ReConBotArm::traj_client_ [private]
Definition at line 50 of file basic_arm.cpp.
Referenced by ~ReConBotArm().
The documentation for this class was generated from the following file:
basic_arm.cpp