joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_2
    joint_speed: 1.0
    motor:
        id: 2
        init: 0
        min: 0
        max: 2048

joint3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_3
    joint_speed: 1.0
    motor:
        id: 3
        init: 2048
        min: 0
        max: 4095

joint6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_6
    joint_speed: 1.0
    motor:
        id: 6
        init: 0
        min: 0
        max: 4095
